### ISSUE TITLE
does not recegnize the wheel action in Angular 18

### ISSUE THREAD

**Issue by pouyababaie** [mrmyroll2/NgScrollPicker#15]
I encountered this error.
if you help me undrestand the logic , i can create a pull request to fix it myself

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at NgScrollPickerComponent.getTouchInfo (ng-scroll-picker.mjs:193:47)
    at NgScrollPickerComponent.getGroupIndexBelongsEvent (ng-scroll-picker.mjs:196:28)
    at NgScrollPickerComponent.handleScroll (ng-scroll-picker.mjs:263:27)
```

To my undrestanding  , the object ``` ev.changedTouchs[0] ``` does not exsit.
i dont think it is a versioning problem but i guess it is somthing related to the event passed as a parameter.

here is a picture to explain myself better 
![image](https://github.com/user-attachments/assets/e21287dc-42f2-4916-a0df-853d428853da)

**Comment by avishaiTabit** [comment]
Did you fix this issue? @pouyababaie

**Comment by pouyababaie** [comment]
@avishaiTabit Not yet. next week maybe

**Comment by half22** [comment]
@pouyababaie did you fix this problem?
